
[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "14"
  MONGO_URL =mongodb+srv://developeraayush145:1DYbUXL8b1zAvehb@your-cluster.mongodb.net/DeveloperAayushWeb

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
